### ISSUE TITLE
Update pets list when adding a new pet

### ISSUE THREAD

**Issue by hronnro** [hronnro/dyrfinna#17]
Re-fetch the "my pets" list after you create a new pet, so you can immediately see the new pet in the list after being brought back to your profile page after creating a pet.

**Comment by axelg12** [comment]
@hronnro Do you have prefernce on how this is implemented? I was thinking if using the React context API would make sense here

**Comment by hronnro** [comment]
@axelg12 welcome!! I think we might want to keep this data global and fetch it on app start, as you should f.ex also be able to access the list of your pets when you're creating a new search -> #11 

I've already implemented the user object using context in [globalState.tsx](https://github.com/hronnro/dyrfinna/blob/f9c479c94b27fbda65e577299e5c6856c360b89a/globalState.tsx)

**Comment by axelg12** [comment]
Should be fixed with #34
