### ISSUE TITLE
Be able to edit my pet

### ISSUE THREAD

**Issue by hronnro** [hronnro/dyrfinna#36]
User should be able to edit their pet from the "My Pets" list on their profile

**Comment by axelg12** [comment]
@hronnro Do you want this to be a new screen or can wew use the same screen as when we register pets, but just pre-fill the fields with the already registered pet data?

So use this scree, but with data from the pet the user clicked in the "My Pet" list?

![Uploading image.png…]()

**Comment by hronnro** [comment]
@axelg12 I think we should definitely reuse the original screen with prefilled info!
